openapi: "3.0.3"
info:
  title: "User Service REST API"
  version: "@project.version@"
security:
  - ApiKeyAuth: [ ]
paths:
  /api/v1/ping:
    get:
      summary: Protected ping endpoint
      tags:
        - ping
      operationId: ping
      security:
        - ApiKeyAuth: [ ]
        - UserServiceToken: [ ]
      responses:
        '200':
          description: Successfully pinged endpoint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
        '400':
          description: Bad Request (Invalid Query Parameters)
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server Error (Failed to fetch logs)
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    PingResponse:
      type: object
      properties:
        text:
          type: string
        username:
          type: string
        uid:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          description: the error code
        message:
          type: string
          description: the errors message
    Id:
      description: 'ID'
      type: string
      format: uuid
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
    UserServiceToken:
      description: 'Must contain an encrypted User Service Token.'
      type: http
      scheme: bearer